//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Nullable<int> Did { get; set; }
        public int ID { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> S_Age { get; set; }
        public string S_Email { get; set; }
        public string S_Password { get; set; }
        public string S_Address { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
